import { BookItem } from '../../redux/modules/book';

const dummyBooks = [
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'B5IIEAAAQBAJ',
    title: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    authors: ['David Thomas', 'Andrew Hunt'],
    selfLink: 'https://www.googleapis.com/books/v1/volumes/B5IIEAAAQBAJ',
    describe: '達人プログラマー 熟達に向けたあなたの旅（第2版）',
    imageUrl:
      'http://books.google.com/books/content?id=B5IIEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
    usersHaveRead: [],
    usersWantRead: [],
    comments: [],
    registeredBy: {
      id: '',
      name: '',
      email: '',
    },
    createdAt: 0,
    updatedAt: 0,
  },
];

export const getBooks = async (): Promise<BookItem[]> => dummyBooks;
